javascript-loops-Kitlong Lai
Kitlonglai/m1-0323-code-solutions pull request #10
Opened 2023-03-31 04:27 UTC by Kitlonglai

<img width="418" alt="Screenshot 2023-03-30 at 9 25 04 PM" src="https://user-images.githubusercontent.com/111219005/229022676-cc631d46-0fe3-4d5b-8e00-a00b239925df.png">

2023-04-02 00:21 UTC, kurtyazdizadeh requested changes
Couple small changes, almost there though!

2023-04-02 00:21 UTC, kurtyazdizadeh commented on javascript-loops/main.js
> +  while (currentNumber < 10) {
this will be short one iteration

2023-04-02 00:21 UTC, kurtyazdizadeh commented on javascript-loops/main.js
> +  while (currentNumber < 20) {
this will also be short by one iteration

2023-04-03 19:32 UTC, kurtyazdizadeh approved these changes
Approved 👍

2023-04-03 20:52 UTC, Kitlonglai commented
<img width="421" alt="Screenshot 2023-04-03 at 8 57 45 AM" src="https://user-images.githubusercontent.com/111219005/229624872-735c30c6-aefd-4bd9-9319-22d76430ab2d.png">
<img width="436" alt="Screenshot 2023-04-03 at 8 57 51 AM" src="https://user-images.githubusercontent.com/111219005/229624891-06a40bf8-ca09-435b-bd32-ae13f92ec191.png">

2023-04-03 20:52 UTC, merged