javascript-objects-Kitlong Lai
Kitlonglai/m1-0323-code-solutions pull request #3
Opened 2023-03-22 04:41 UTC by Kitlonglai

<img width="435" alt="Screenshot 2023-03-21 at 9 35 50 PM" src="https://user-images.githubusercontent.com/111219005/226803819-397cd8cc-1f66-48b2-9e72-361dabb23778.png">
exercise.

2023-03-22 04:46 UTC, kurtyazdizadeh requested changes
Just a couple changes, please review the comments for more details

2023-03-22 04:46 UTC, kurtyazdizadeh commented on javascript-objects/main.js
> +const fullName = student.firstName + student.lastName;
This will evaluate to `KitlongLai` - we should add a `space` character in this string concatenation.

2023-03-22 04:46 UTC, kurtyazdizadeh commented on javascript-objects/main.js
> +vehicle.color = 'chalk';
Let's make sure to practice using bracket notation (lines 18-21) instead of dot notation here.

2023-03-23 02:22 UTC, Kitlonglai commented
<img width="431" alt="Screenshot 2023-03-22 at 6 59 47 PM" src="https://user-images.githubusercontent.com/111219005/227083369-6582e083-3271-4353-8c1d-533c5ac2f61c.png">

2023-03-23 05:18 UTC, Kitlonglai commented
<img width="421" alt="Screenshot 2023-03-22 at 10 13 25 PM" src="https://user-images.githubusercontent.com/111219005/227110292-e0764a3d-d15a-4112-820d-539944ee6149.png">

2023-03-23 16:22 UTC, kurtyazdizadeh approved these changes
Approved, nice work 👍

2023-03-23 17:10 UTC, merged