javascript-conditionals-Kitlong Lai
Kitlonglai/m1-0323-code-solutions pull request #9
Opened 2023-03-29 05:02 UTC by Kitlonglai

<img width="437" alt="Screenshot 2023-03-28 at 9 59 11 PM" src="https://user-images.githubusercontent.com/111219005/228431543-c12302e9-c80b-490d-b34c-036118d38479.png">

2023-03-30 05:45 UTC, kurtyazdizadeh requested changes
See comments, just a small change so that those last two functions are return functions and not void functions.

2023-03-30 05:45 UTC, kurtyazdizadeh commented on javascript-conditionals/main.js
> +      console.log("We're the warner brothers!");
these should be `return`ed back out of the function instead of a console log

2023-03-30 05:45 UTC, kurtyazdizadeh commented on javascript-conditionals/main.js
> +      console.log('Matrix');
Same here

2023-03-30 23:08 UTC, Kitlonglai commented
![Uploading Screenshot 2023-03-30 at 12.02.18 AM.png…]()

2023-03-30 23:10 UTC, Kitlonglai commented
<img width="444" alt="Screenshot 2023-03-30 at 12 02 18 AM" src="https://user-images.githubusercontent.com/111219005/228984554-9154d6da-30f0-4305-809c-37834e5bd21c.png">

2023-03-31 01:10 UTC, kurtyazdizadeh approved these changes
Approved 👍

2023-03-31 01:29 UTC, merged